### ISSUE TITLE
Amélioratoin de la scène

### ISSUE THREAD

**Issue by adriens** [adriens/opt-temps-attente-agences-unity#1]
# Idée générale

L'idée est de rendre la scène toujours plus belle  à contempler et permettre de comprendre ce que l'on regarde.

# Premières Idées

- [x] Surface : texture velours vers type tapis de billard ou mince surface d'eau qui permettrait de laisser de beax sillages au passage de la boule, des interférences entre les sillages
- [ ] OPT neon logo : en mode neon/pancarte, intégrer le logo de l'OPT comme on peut le voir sur le motels, dans les rues de Hong Kong ou encore dans les photos de Blade Runer
- [x] Lampe au-dessus du tapis de billard : en mode lampe de billard : sombre autour de la table, afin de mettre le focus sur la scène (tapis et boules)

**Comment by gbertherat** [comment]
Je ne sais pas ou mettre le logo OPT, et je ne sais pas si c'est possible de faire du néon sans refaire le logo en 3D. Pour l'instant ça ressemble à ça
![image](https://user-images.githubusercontent.com/61923651/100556415-6dc67b80-32f6-11eb-83ff-68cd2584f2f2.png)

**Comment by adriens** [comment]
Je l'imaginais en mode pancarte verticale, comme les panneaux publicitaires... à terme on porrait même y charger un contenu
