### ISSUE TITLE
Collision et particules

### ISSUE THREAD

**Issue by adriens** [adriens/opt-temps-attente-agences-unity#2]
Comme effet de collisions, explorer:

- [ ] Génération de particules
- [x] Illumination des boules qui entrent en colliision, cela pourrait être très beau à contempler, comme une sorte de guirlande de Noël. L'intensité et la durée de l'illumination serait fonction de la violence du choc par exemple

**Comment by gbertherat** [comment]
Les particules rendent pas bien :(

**Comment by adriens** [comment]
Mais le boulot sur les lumières oui 👏
