### ISSUE TITLE
Affichage metadatas

### ISSUE THREAD

**Issue by adriens** [adriens/opt-temps-attente-agences-unity#3]
Lorsque je touche une boule, faire apparaître un drapeau/flag sur lequel on affiche les propriétés de la boule:

- temps attente
- nom agence

Un seul drapeau à la fois est affichable

# NB

Voir si c'est pas plu ssimple d'afficher ces finfos en mode score sur le côté dans un menu par exemple

**Comment by gbertherat** [comment]
@adriens Avec un effet de contour sur l'objet visé et un crosshair
![image(1)](https://user-images.githubusercontent.com/61923651/101858403-a2bbb380-3bbd-11eb-9e27-9d8f4327d952.png)
